version: '3.7'

services:
  chrome:
    image: selenium/node-chrome:beta
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_VNC_NO_PASSWORD=true
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_MAX_INSTANCES=3
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  # edge:
  #   image: selenium/node-edge:4.18.1-20240224
  #   shm_size: 2gb
  #   depends_on:
  #     - selenium
  #   environment:
  #     - SE_VNC_NO_PASSWORD=true
  #     - SE_NODE_OVERRIDE_MAX_SESSIONS=true
  #     - SE_NODE_MAX_SESSIONS=3
  #     - SE_NODE_MAX_INSTANCES=3
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #   ports:
  #     - "6901:5900"
  firefox:
    image: selenium/node-firefox:beta
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_VNC_NO_PASSWORD=true
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_MAX_INSTANCES=3
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  selenium-hub:
    environment:
        - SE_NODE_SESSION_TIMEOUT=999999999
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  selenium: # Need to run only on dev mode
    image: selenium/standalone-firefox:latest
    environment:
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "4445:4444" # Selenium
      - "7900:7900" # VNC server